name = "portfolio"
compatibility_date = "2024-04-10"

[build]
command = "npm run build"

[site]
bucket = ".next/static"
entry-point = "./"

[env.production]
routes = [
  { pattern = "/*", zone_name = "cartertran.com" }
]

[[build.upload]]
type = "static"
dir = ".next/static"